name = "tecs"
description = "A library with another ECS implmentation"
version = "0.3.0-dev"

authors = ["Ihar Tsalka"]
maintainers = ["Ihar Tsalka <git@tsobako.me>"]
maintainers-logins = ["tsobako"]
licenses = "MIT"
website = ""
tags = ["ecs", "gamedev"]
